import asyncio
import httpx
import uuid
import secrets
from datetime import datetime, timezone
import random
from config import COMMAND_NODE_URL

try:
    from faker import Faker
    fake = Faker()
except ImportError:
    print("Please install faker: pip install faker")
    exit(1)

async def send_report(client, report_id, operator_id):
    disasters = [
        ("structural_collapse", "critical"),
        ("flash_flood", "high"),
        ("chemical_spill", "critical"),
        ("wildfire", "high"),
        ("gas_leak", "critical"),
    ]
    cat, tlevel = secrets.choice(disasters)
    lat = 46.21 + random.uniform(-0.02, 0.02)
    lon = -123.82 + random.uniform(-0.02, 0.02)

    payload = {
        "report_id": report_id,
        "operator_id": operator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "location": {"latitude": round(lat, 4), "longitude": round(lon, 4)},
        "audio_transcript": f"Mock report generated by chaos monkey. {cat} reported.",
        "image_analysis": f"Simulated analysis for {cat}.",
        "threat_level": tlevel,
        "category": cat,
        "confidence": round(random.uniform(0.7, 0.99), 2),
        "raw_audio_duration_s": 10.5,
        "model_backend": "chaos_monkey"
    }
    
    url = f"{COMMAND_NODE_URL}/api/v1/field-report"
    try:
        # Spread out requests slightly to mimic real traffic
        await asyncio.sleep(random.uniform(0.1, 3.0))
        response = await client.post(url, json=payload, timeout=60.0)
        return response.status_code
    except Exception as e:
        return str(e)

async def main():
    print("🚀 AEGIS DISASTER TRAFFIC SIMULATOR 🚀")
    print(f"Blasting Command Node at {COMMAND_NODE_URL} with 30 concurrent field reports...")
    print("Watch the dashboard map!")
    
    async with httpx.AsyncClient() as client:
        tasks = []
        for i in range(30):
            operator_id = f"{fake.last_name().upper()}-{secrets.choice(['Alpha', 'Bravo', 'Charlie', 'Delta'])}"
            report_id = f"chaos-{uuid.uuid4().hex[:6]}"
            tasks.append(send_report(client, report_id, operator_id))
            
        results = await asyncio.gather(*tasks)
        
    success = sum(1 for r in results if r == 200)
    print(f"\n✅ Completed. {success}/30 reports successfully processed by Command Center.")

if __name__ == "__main__":
    asyncio.run(main())
